assets:
  caching:
    enabled: true
    path: .jekyll-cache/assets
    type: file
  compress:
    css: /assets/css/*.css
    img: /assets/**/*.{jpg,png}
    js: /assets/js/*.js
  compression: true
  gzip:
    - text/css
    - application/javascript
  plugins:
    css:
      autoprefixer: {}
    img:
      optim: {}
  precompile: []
  raw_precompile: []
  source_maps: false
  sources:
    - assets/css
    - assets/icons
    - assets/images
    - assets/videos
    - assets/js
author: Sebastian Rousseau
author_facebook: eaglerex
background_color: '#fff'
baseurl: ''
compress_html:
  blanklines: false
  clippings: all
  comments: all
  endings: all
  profile: true
  startings: all
description: Eagle Rex description
email: hello@eaglerex.com
encoding: utf-8
excerpt_separator: <!--more-->
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .jekyll-cache
  - .sass-cache
  - .travis.yml
  - '*.sublime-project'
  - '*.sublime-workspace'
  - Capfile
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - README.md
  - tmp
  - vendor/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - yarn.lock
facebook_id: 10156052650356912
facebook_username: eaglerex
feed:
  path: atom.xml
github_username: sebastienrousseau
google_analytics: G-X7J1L6Q2D2
highlighter: rouge
include:
  - assets
  - _pages
jekyll-minifier:
  keep_files:
    - .git
  uglifier_args:
    harmony: true
kramdown:
  auto_ids: true
  enable_coderay: false
  entity_output: as_char
  hard_wrap: false
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..3
kramdown:auto_ids: true
lang: en
linkedin_username: eaglerex
locale: en_gb
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
repository: sebastienrousseau/eaglerex.com
sass:
  sass_dir: _scss
  style: compressed
source: source
styles: /assets/css/main.css
subtitle: Dare to Soar
theme-color: '#000'
title: Eagle Rex Cycling Club
twitter_creator: wwdseb
twitter_username: eaglerex
url: https://eaglerex.com
version: 1.0.5
workbox:
  dest_js_directory: assets/js
  precache_glob_directory: /
  precache_glob_ignores:
    - assets/videos/**/*
    - sw-register.js
  precache_glob_patterns:
    - '{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}'
    - index.html
  precache_recent_posts_num: 5
  sw_dest_filename: sw.js
  sw_src_filepath: sw.js
